-- CREAR BASE DE DATOS KRATOS
--CREATE DATABASE KRATOSDB;
--GO

USE KRATOSDB;
GO

-- TABLA DE ROLES
CREATE TABLE ROLES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION NVARCHAR(200),
    ACTIVO BIT DEFAULT 1,
    FECHA_CREACION DATETIME DEFAULT GETDATE()
);

-- TABLA DE USUARIOS
CREATE TABLE USUARIOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EMAIL NVARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    NIF NVARCHAR(20) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
	TELEFONO NVARCHAR(50) NOT NULL,
	TELEFONO2 NVARCHAR(50) NOT NULL,
    ROL_ID INT NOT NULL,
	CLIENTE_ID INT NULL,
    ACTIVO BIT DEFAULT 1,
    ULTIMO_LOGIN DATETIME,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ROL_ID) REFERENCES ROLES(ID)
);

-- TABLA DE EMPRESAS
CREATE TABLE EMPRESAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(200) NOT NULL,
	CIF NVARCHAR(20) NOT NULL,
    RUT NVARCHAR(20) UNIQUE,
    DIRECCION NVARCHAR(300),
    TELEFONO NVARCHAR(20),
	TELEFONO2 NVARCHAR(20),
    EMAIL NVARCHAR(100),
	EMAIL2 NVARCHAR(100),
    ACTIVO BIT DEFAULT 1,
    FECHA_CREACION DATETIME DEFAULT GETDATE()
);

-- TABLA DE OPERACIONES
CREATE TABLE OPERACIONES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EMPRESA_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    TIPO_OPERACION NVARCHAR(50) NOT NULL,
    MONTO DECIMAL(15,2),
    ESTADO NVARCHAR(30) DEFAULT 'PENDIENTE',
    DESCRIPCION NVARCHAR(500),
    FECHA_OPERACION DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);

-- TABLA DE SESIONES PARA MANEJO DE TOKENS
CREATE TABLE SESIONES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    TOKEN NVARCHAR(500) NOT NULL,
    FECHA_EXPIRACION DATETIME NOT NULL,
    ACTIVO BIT DEFAULT 1,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);
